- block:
    - name: populate service facts
      service_facts:

    - name: stop prez-ui
      systemd:
        name: container-prez-ui
        state: stopped
        daemon_reload: true
      when: "'container-prez-ui.service' in services"

    - name: copy .env from host to target /home/ubuntu/.env
      ansible.builtin.copy:
        src: .env
        dest: /home/ubuntu/.env
        owner: root
        mode: "0644"

    - name: create prez-ui container with a systemd service file managed by systemctl
      containers.podman.podman_container:
        name: prez-ui
        image: "{{ prez_ui_image }}"
        state: present
        ports:
          - "8001:80"
        generate_systemd:
          path: /etc/systemd/system/
          restart_policy: always
        env:
          VOCPREZ_SPARQL_ENDPOINT: http://0.0.0.0:3030/gsq
        volume:
          - /home/ubuntu/.env:/.env

    - name: enable prez-ui service
      systemd:
        name: container-prez-ui
        enabled: true
        daemon_reload: true

    - name: start prez-ui
      systemd:
        name: container-prez-ui
        state: started
        daemon_reload: true

  become: true
